//common constant file
module.exports = message = {
    VALIDATION_ERROR: "VALIDATION ERROR",
    EMPTY_FIELDS: "EMPTY FIELDS",
    USER_VALIDATION: "YOU ARE NOT A VALID USER",
    NO_TOKEN_PROVIDED: "PLEASE PROVIDE TOKEN",
    TOKEN_EXPIRE: "TOKEN EXPIRED",

    DATA_NOT_FOUND: "DATA NOT FOUND",

    INVALID_CREDENTIAL: "INVALID USERNAME OR PASSWORD",

    CATEGORY_ADDED: "CATEGORY HAS BEEN ADDED SUCCESSFULLY",
    CATEGORY_EXIST: "CATEGORY ALLREADY EXIST WITH THIS NAME",
    CATEGORY_LIST: "FIND CATEGORY LIST HERE",

    SUB_CATEGORY_ADDED: "SUB CATEGORY ADDED SUCCESSFULLY",
    SUB_CATEGORY_EXIST: "SUB CATEGORY ALLREADY EXIST",
    SUB_CATEGORY_LIST: "FIND SUB CATEGORY LIST HERE",
    SUB_CATEGORY_DELETED: "SUB CATEGORY DELETED",
    SUB_CATEGORY_ID_NOT_EXIST: "GIVEN SUB CATEGORY NOT EXIST",

    OFFER_ADDED: "OFFER HAS BEEN ADDED SUCCESSFULLY",
    OFFER_EXIST: "OFFER ALLREADY EXIST",
    OFFER_UPDATED: "OFFER UPDATED SUCCESSFULLY",
    OFFER_LIST: "FIND OFFER LIST HERE",
    OFFER_DELETED: "OFFER HAS BEEN DELETED",

    PRODUCT_ADDED: "PRODUCT HAS BEEN ADDED SUCCESSFULLY",
    PRODUCT_LIST: "FIND PRODUCT LIST HERE",
    PRODUCT_UPDATED: "PROODUCT UPDATED SUCCESSFULLY",
    PRODUCT_DELETED: "PRODUCT DELTED SUCCESSFULLY",
    INVALID_PRODUCT_ID: "INVALID PRODUCT ID",

    PRIVACY_POLICY_EXIST: "PRIVACY POLICY ALLREADY EXIST",
    PRIVACY_POLICY_ADDED: "PRIVACY POLICY ADDED SUCCESSFULLY",
    PRIVACY_POLICY: "FIND PRIVACY POLICY HERE",

    TERM_AND_CONDITION_EXIST: "TERM AND CONDITION ALLREADY EXIST",
    TERM_AND_CONDITION_ADDED: "TERM AND CONDITION ADDED SUCCESSFULLY",
    TERM_AND_CONDITION: "FIND TERM AND CONDITION HERE",

    INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR",

    EMAIL_EXIST: "EMAIL ALLREADY EXIST PLEASE USE DIFFRENT",

    REGISTRATION_SUCCESSFULLY: "YOU HAVE REGISTERED SUCCESSFULLY",
    PASSWORD_CHANGED: "YOUR PASSWORD HAS BEEN CHHANGED SUCCESSFULLY",
    LOGIN: "YOU HAVE LOGIN SUCCESSFULLY",
    PROFILE_UPDATED: "PROFILE HAS BEEN UPDATED",
    PHONE_UPDATED: "PHONE NUMBER UPDATTED",
    PROFILE_DELETED: "PROFILE HAS BEEN DELETED",


    OLD_PASSWORD: "INVALID OLD PASSWORD",
    RESET_PASSWORD_LINK: "LINK HAS BEEN SEND ON YOUR MAIL PLEASE CHECK",

    CART_CREATED: "YOUR CART HAS BEEN CREATED",
    CHECK_CART: "FIND YOUR CART HERE",
    ADD_PRODUCT_TO_CART: "PRODUCT HAS BEEN ADDED TO CART",
    REMOVE_PRODUCT_FROM_CART: "PRODUCT REMOVED FROM CART",
    DELETE_CART: "PRODUCT REMOVED FROM YOUR CART",

    ORDER_DETAIL: "FIND YOUR ORDER DETAIL HERE",
    INVALID_coupon: "INVALID COUPON CODE",

    CARD_ADDED: "YOUR CARD HAS BEEN ADDED SUCCESSFULLY",
    CARD_LIST: "FIND CARD LIST HERE",
    CARD_UPDATE: "YOUR CARD HAS BEEN UPDATED",
    CARD_DELETE: "YOUR CARD HAS BEEN DELETED SUCCESFULLY",

    CONTECT_US_ADDED: "YOU HAVE SUBMITTET SUCCESSFULLY",
    CONTECT_US: "CONTECT US LIST",

    QUANTITY: "order product quantity should be less then acctual product quantity",

    ORDER_PLACED: "YOUR ORDER HAS BEEN PLACED",
    ORDER_ACCEPTED: "ORDER STATUS HAS BEEN CHANGED ACCEPTED",
    ORDER_CANCEL: "ORDER STATUS HAS BEEN CANCELLED",
    ORDER_IN_TRANSIT: "ORDER STATUS IS IN TRANSIT NOW",
    ORDER_DELEVERED: "ORDER HAS DELIVERED NOW",
    ORDER_PENDING: "ORDER STATUS IS PENDING",
    INVALID_ORDER_STATUS: "PLEASE ENTER A VALID STATUS, 1 FOR PENDING, 3 FOR CANCEL, 4 FOR IN TRANSIT, 5 FOR DELIVERED ",

    PAYMENT_SUCCESSFULL: "PAYMENT HAS BEEN SUCCESSFULL",

    FAQ_ADDED: "FAQ ADDED SUCCESSFULLY",
    ANS_ADDED: "YOUR ANSWER HAS BEEN ADDED",
    FAQ_DELETE: "FAQ HAS BEEN DELETED",

    NOTIFICATION: "NOTICATION LIST"

}